#!/usr/bin/env node
require('dotenv').config();
const { execSync } = require('child_process');
const path = require('path');

const inputCmd = process.argv.slice(2).join(' ');
if (inputCmd === '--info') {
  const uiPkg = require(path.join(__dirname, 'ui/package.json'))
  console.log(`Current delta-ui: ${uiPkg.version}`);

  process.exit();
}

const configFile = path.join(__dirname, '../delta.config.js');
process.env.DELTA_CONFIG_PATH = process.env.DELTA_CONFIG_PATH || configFile;

const rootDir = path.join(__dirname, '../');

if (inputCmd === 'test') {
  const jestCli = path.join(__dirname, 'ui/node_modules/jest/bin/jest.js');
  const jestConfig = path.join(__dirname, 'ui/jest.config.js');
  const cmd = `node ${jestCli} ui/content-tests/* -c ${jestConfig}`;

  execSync(cmd, { stdio: 'inherit', cwd: path.join(__dirname, 'ui') });
  process.exit();
}

const gulpCli = path.join(__dirname, 'ui/node_modules/gulp-cli/bin/gulp.js');
const gulpConfig = path.join(__dirname, 'ui/gulpfile.js');

const cmd = `node ${gulpCli} --cwd ${rootDir} -f ${gulpConfig} ${inputCmd} --delta-config ${configFile}`;

execSync(cmd, { stdio: 'inherit' });
