name: Preview build with VEDA UI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-version]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  makepr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.event.client_payload.ref }}
    - name: Use Node.js ${{ env.NODE }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE }}

    - name: Set Version Variable
      id: set-version
      run: echo "VERSION=${{ github.event.client_payload.VERSION_NUMBER || 'v5.11.0' }}" >> $GITHUB_ENV
  
    - name: git config
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Update Submodule
      shell: bash
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
        cd ./.veda/ui
        git fetch --tags
        git checkout ${{ env.VERSION }}
        cd -
        git checkout -b ci-${{ env.VERSION }}
        git add .veda/ui
        git commit -m "Update submodule to version ${{ env.VERSION }}"
        git push origin ci-${{ env.VERSION }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: "Update UI to ${{ env.VERSION }}"
        title: "Update submodule to version${{ env.VERSION }}"
        body: "This PR updates the submodule to version `${{ env.VERSION }}`."
        base: develop
        branch: ci-${{ env.VERSION }}